# Generated by Django 5.2.8 on 2025-11-17 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(help_text='La opción seleccionada por el votante.', max_length=100)),
                ('digital_signature', models.TextField(help_text='Firma digital (Hash RSA) del voto, prueba de no repudio.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(help_text='Perfil del votante que emitió este voto.', on_delete=django.db.models.deletion.CASCADE, to='voting.voterprofile')),
            ],
        ),
    ]
