# Generated by Django 5.2.8 on 2025-11-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='encrypted_vote',
            field=models.TextField(blank=True, help_text='Voto cifrado con AES-256 para demostrar confidencialidad.', null=True),
        ),
    ]
